# format = """
# [╭─user───❯](bold blue) $username
# [┣─system─❯](bold yellow) $hostname
# [┣─project❯](bold red) $directory$git_branch$git_state$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs$conda$dart$elixir$elm$erlang$java$julia$kotlin$nim$ocaml$perl$php$ruby$scala$swift$zig$rust
# [╰─cmd────❯](bold green)
# """

format = """$os$battery$directory$python$conda
$sudo$character"""
# continuation_prompt = "[∙](bright-black) "

# format = """$os$username$hostname$battery$directory
# $character"""
right_format = """$git_branch\
$git_state\
$git_status\
$package\
$c\
$cmake\
$java\
$golang\
$meson\
$jobs\
$kotlin\
$lua\
$bun
$time
"""

[time]
disabled = false
time_format = "%R"   # Hour:Minute Format
style = "bold white"
# format = '  $time($style)'
format = '\[  [$time]($style)\]'

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

# ~/.config/starship.toml

[sudo]
style = 'italic green'
# symbol = '👩‍💻 '
disabled = false

[hostname]
ssh_symbol = " "
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red)"


[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 60


#  
# configure directory
[directory]
read_only = " 󰌾 "
truncation_length = 10
# truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false               # truncates directory to root folder if in github repo
before_repo_root_style = "italic blue"
repo_root_style = "bold italic yellow"
style = "italic blue"

[directory.substitutions]
"Documentos" = "󰈙 "
"Descargas" = " "
"Música" = " "
"Imagenes" = " "
"Público" = "󰈙 "
"Plantillas" = "󰈙 "
"Proyectos" = " "

[cmd_duration]
min_time = 10
show_milliseconds = false
disabled = false
style = "bold italic red"
format = '\[[⏱ $duration]($style)\]'

[aws]
symbol = "  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[conda]
# symbol = " "
symbol = '🅒 '
# symbol = 'PyEnv:'
# format = 'in [$symbol$environment]($style)'
format = 'in [$environment]($style)'
ignore_base = false
style = "green italic"

[dart]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = " "
commands = [["cc", "--version"], ["gcc", "--version"], ["clang", "--version"]]
detect_extensions = ["**/src/**.c", "**/include/**.h"]
detect_files = ["Makefile"]
style = "bold blue"


[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\] '
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false
#c++ package


[elixir]
symbol = " "


[cmake]
disabled = false
# format = "via [$symbol $version]($style) "
format = '\[[$symbol ($version)]($style)\]'
symbol = "CMAKE"
# symbol = " "
style = "italic green"

[elm]
symbol = " "

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count} "
behind = "🐢 ×${count} "
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count} "
untracked = "🛤️  ×${count} "
stashed = "📦 "
modified = "📝 ×${count} "
staged = "🗃️  ×${count} "
renamed = "📛 ×${count} "
deleted = "🗑️  ×${count} "
style = "bright-white"
#  format = "$all_status $ahead_behind"
format = '([\[$all_status$ahead_behind\]]($style))'


# format = '([\[$all_status$ahead_behind\]]($style) )'
# stashed = "[${count}*](green)"
# modified = "[${count}+](yellow)"
# deleted = "[${count}-](red)"
# conflicted = "[${count}~](red)"
# ahead = "⇡${count}"
# behind = "⇣${count}"
# untracked = "[${count}?](blue)"
# staged = "[${count}+](green)"

[git_state]
style = "bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "


[nix_shell]
symbol = " "


[perl]
symbol = " "

[php]
symbol = " "


[python]
symbol = "🐍 "
pyenv_version_name = true
format = 'via [${symbol}python(\($virtualenv\)) ]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python","./.venv/bin/python","./env/bin/python","./.env/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
disabled = false
detect_files = ["pyproject.toml", "requirements.txt", "Pipfile"] # Add common project files
detect_folders = [".venv", "venv"] # Add common virtual env folder names

[ruby]
symbol = " "

[kotlin]
symbol = " "

[gradle]
# symbol = "\ue7f2"
symbol = " "

[rust]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = " "

[shlvl]
symbol = " "


[nodejs]
format = "via [  Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]


[buf]
symbol = " "


[fossil_branch]
symbol = " "


[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "


[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[os]
format = '[$symbol]($style)'
disabled = false


# This is the default symbols table.
[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = "💠 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "󰣇 "
Artix = "󰣇 "
CachyOS = "󰣇 "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Macos = "🍎 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
Nobara = "🎩 "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "💠 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = "🎯 "
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = "  "
Windows = "🪟 "

# [os.symbols]
# Alpaquita = " "
# Alpine = " "
# Amazon = " "
# Android = " "
# Arch = " "
# Artix = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "󰛓 "
# Gentoo = " "
# HardenedBSD = "󰞌 "
# Illumos = "󰈸 "
# Linux = " "
# Mabox = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = "󰈺 "
# openSUSE = " "
# OracleLinux = "󰌷 "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# Redox = "󰀘 "
# Solus = "󰠳 "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "


[rlang]
symbol = "󰟔 "
