#!/usr/bin/env bash

# echo "Running LaTeX container with user $(id -u):$(id -g)"

# echo "Mounting current directory $(pwd) to /data"

# -i --user="$(id -u):$(id -g)"

program="$(basename $0)"
args= "$@"

podman run --rm -v $(pwd):/data mingc/latex $program $args