#!/usr/bin/env bash

# echo "Running LaTeX container with user $(id -u):$(id -g)"

# echo "Mounting current directory $(pwd) to /data"

# -i --user="$(id -u):$(id -g)"

program="$(basename $0)"
args= "$@"

docker run --rm -v $(pwd):/data dockershelf/latex $program  $args
