general {
    lock_cmd = pidof swaylock || swaylock -f -c 000000
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Listener principal que maneja el estado del cargador
listener {
    timeout = 300                                                    # 5 minutos
    on-timeout = ~/.config/hypr/scripts/power-aware-idle.sh         # Script que decide según el estado del cargador
    on-resume = ~/.config/hypr/scripts/power-aware-resume.sh        # Script de recuperación
}

# Listener adicional para apagar pantalla (independiente del cargador)
listener {
    timeout = 600                                                   # 10 minutos
    on-timeout =
     hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}